repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.10
    hooks:
      # Run the linter
      - id: ruff-check
        args: [--fix]
        files: ^src/
      # Run the formatter
      - id: ruff-format
        args: []
        files: ^src/

  # https://github.com/astral-sh/ty/issues/269
  # to add "ty" to pre-commit