version: 1
disable_existing_loggers: true
formatters:
  json:
    class: pythonjsonlogger.json.JsonFormatter
    format: "%(asctime)s %(levelname)s %(name)s %(message)s"
  #    rename_fields:
  #      levelname: "level"
  #      asctime: "timestamp"

  standard:
    format: "%(asctime)s [%(levelname)s] %(name)s: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: json
    stream: ext://sys.stdout

#  file:
#    class: logging.handlers.RotatingFileHandler
#    level: DEBUG
#    formatter: json
#    filename: debug.log
#    maxBytes: 10485760 # 10 MB
#    backupCount: 3
#    encoding: utf8

loggers:
  #  jsonFileLogger:
  #    level: DEBUG
  #    handlers: [file]
  #    # propagate: no

  jsonConsoleLogger:
    level: DEBUG
    handlers: [ console ]

root:
  level: NOTSET
  handlers: [ ]